name: Build Kernel NYX

on:
  workflow_dispatch:
    inputs:
      token:
          description: 'Telegram bot token'
          required: true
      chat_id:
          description: 'Telegram chat id'
          required: true


env:
  TZ: Asia/Jakarta
  DEVICE: wayne
  REPO: https://github.com/Ariden24/Nyx_kernel_xiaomi_sdm660-4.19
  BRANCH: nyx_mod
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "ariden"
          git config --global user.email "debbyariansyah24@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch
          neofetch

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "wayne" ]; then
            wget https://raw.githubusercontent.com/Ariden24/kernel_build_action/main/scripts/wayne_build_script.sh
            bash nyx_build_script.sh
          else
            echo "Device not supported yet"
          fi

